[versions]
guava = "33.2.1-jre"
junit-jupiter = "5.10.3"
kotest = "5.9.0"
ktlint = "12.1.2"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }